from __future__ import annotations

import functools
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import dataclasses as dcs
    from collections.abc import Callable
    from pathlib import Path


class ProtoTask(Protocol):
    @property
    def task(self) -> str: ...
    @property
    def children(self) -> list[ProtoTask]: ...
    @property
    def chain(self) -> list[dict]: ...

    @property
    def seq_name(self) -> str: ...

    @functools.cached_property
    def parent(self) -> ProtoTask | None: ...

    def ancestor(self, idx: int = -1) -> ProtoTask | None: ...

    def fields(self, exclude_if: Callable[[dcs.Field], bool] = lambda f: not f.init) -> dict: ...

    def to_dicts(self, exclude_if: Callable[[dcs.Field], bool] = lambda f: not f.init) -> list[dict]: ...

    @staticmethod
    def from_dicts(chain: list[dict]) -> ProtoTask: ...

    def to_json(self, pretty: bool = False) -> str: ...

    @functools.cached_property
    def hash(self) -> str: ...

    @property
    def shorthash(self) -> str: ...

    @functools.cached_property
    def self_tag(self) -> str: ...

    @functools.cached_property
    def tag(self) -> str: ...

    @functools.cached_property
    def dstdir(self) -> Path: ...

    def dump_taskinfo(self, target: Path | None = None) -> None: ...

    def run(self) -> None: ...
