from __future__ import annotations

import functools
from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Protocol, SupportsIndex, overload

if TYPE_CHECKING:
    import dataclasses as dcs
    from pathlib import Path


class ProtoChain(Sequence):
    @property
    def objs(self) -> list[dict]: ...

    @overload
    def __getitem__(self, idx: SupportsIndex) -> ProtoTask: ...

    @overload
    def __getitem__(self, idx: slice) -> ProtoChain: ...

    def copy(self) -> ProtoChain: ...


class ProtoTask(Protocol):
    @property
    def task(self) -> str: ...
    @property
    def children(self) -> list[ProtoTask]: ...
    @property
    def chain(self) -> ProtoChain: ...

    @property
    def seq_name(self) -> str: ...

    @functools.cached_property
    def parent(self) -> ProtoTask | None: ...

    def fields(self, exclude_if: Callable[[dcs.Field], bool] = lambda f: not f.init) -> dict: ...

    def to_dicts(self, exclude_if: Callable[[dcs.Field], bool] = lambda f: not f.init) -> list[dict]: ...

    @classmethod
    def from_dicts(cls, objs: list[dict]) -> ProtoTask: ...

    def to_json(self, pretty: bool = False) -> str: ...

    @functools.cached_property
    def hash(self) -> str: ...

    @property
    def shorthash(self) -> str: ...

    @functools.cached_property
    def self_tag(self) -> str: ...

    @functools.cached_property
    def tag(self) -> str: ...

    @functools.cached_property
    def dstdir(self) -> Path: ...

    def dump_taskinfo(self, target: Path | None = None) -> None: ...

    def run(self) -> bool: ...
